### ISSUE TITLE
Py3k compatibility & doc

### ISSUE THREAD

**Issue by ulikoehler** [vls/cffi_re2#1]
Hi,
firstly, thanks for your awesome work on this library.
As this project currently is not compatbile with Py3k (and I really dislike the pyre2 stuff from Facebook) and is lacking documentation, I decided to put some work into optimizing it.

Py3k already seems to work, see my fork: https://github.com/ulikoehler/cffi_re2/.

I'll add more tests and possibly a partially re-api-compatible layer and then I'll test this library in production in https://github.com/ulikoehler/KATranslationCheck.

Would you be willing to merge my changes once I get it working?

**Comment by ulikoehler** [comment]
I have also added group capturing and I am currently adding findall() support

**Comment by vls** [comment]
​Hi,

Thanks for optimizing it. Looking forward to your PR :)

Thanks

Liang Zhaohao

2015-12-31 9:27 GMT+08:00 Uli Köhler notifications@github.com:

**Comment by ulikoehler** [comment]
Thanks! I submitted a first PR here: https://github.com/vls/cffi_re2/pull/2
